/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuditInput = IDL.Record({
  'inputCsvUrl' : IDL.Opt(IDL.Text),
  'inputText' : IDL.Opt(IDL.Text),
  'selectedBiasDimensions' : IDL.Vec(IDL.Text),
  'summaryTone' : IDL.Text,
  'modelProvider' : IDL.Opt(IDL.Text),
  'jurisdiction' : IDL.Text,
  'selectedSafetyChecks' : IDL.Vec(IDL.Text),
  'deploymentContext' : IDL.Text,
  'outputCount' : IDL.Opt(IDL.Nat),
  'modelVersion' : IDL.Opt(IDL.Text),
  'modelName' : IDL.Text,
  'reportTitle' : IDL.Opt(IDL.Text),
  'intendedPopulation' : IDL.Text,
  'selectedFrameworks' : IDL.Vec(IDL.Text),
});
export const AuditId = IDL.Text;
export const AuditStatus = IDL.Variant({
  'pending' : IDL.Null,
  'complete' : IDL.Null,
  'processing' : IDL.Null,
  'failed' : IDL.Null,
});
export const RiskTier = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'critical' : IDL.Null,
  'medium' : IDL.Null,
});
export const AuditRecord = IDL.Record({
  'id' : AuditId,
  'status' : AuditStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'biasResults' : IDL.Opt(IDL.Text),
  'inputCsvUrl' : IDL.Opt(IDL.Text),
  'inputText' : IDL.Opt(IDL.Text),
  'inputSummary' : IDL.Opt(IDL.Text),
  'regulatoryResults' : IDL.Opt(IDL.Text),
  'selectedBiasDimensions' : IDL.Vec(IDL.Text),
  'overallScore' : IDL.Opt(IDL.Float64),
  'summaryTone' : IDL.Text,
  'orgId' : IDL.Text,
  'recommendations' : IDL.Opt(IDL.Text),
  'createdAt' : IDL.Int,
  'createdBy' : IDL.Text,
  'safetyResults' : IDL.Opt(IDL.Text),
  'riskTier' : IDL.Opt(RiskTier),
  'modelProvider' : IDL.Opt(IDL.Text),
  'verdict' : IDL.Opt(IDL.Text),
  'jurisdiction' : IDL.Text,
  'selectedSafetyChecks' : IDL.Vec(IDL.Text),
  'deploymentContext' : IDL.Text,
  'outputCount' : IDL.Opt(IDL.Nat),
  'modelVersion' : IDL.Opt(IDL.Text),
  'modelName' : IDL.Text,
  'reportTitle' : IDL.Opt(IDL.Text),
  'intendedPopulation' : IDL.Text,
  'selectedFrameworks' : IDL.Vec(IDL.Text),
});
export const DashboardStats = IDL.Record({
  'reportsGenerated' : IDL.Nat,
  'totalAudits' : IDL.Nat,
  'avgRiskScore' : IDL.Float64,
  'openIssues' : IDL.Nat,
});
export const ActivityEvent = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'auditId' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'eventType' : IDL.Text,
});
export const ApiKeyRecord = IDL.Record({
  'id' : IDL.Text,
  'key' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'lastUsed' : IDL.Opt(IDL.Int),
});
export const AuditSummary = IDL.Record({
  'id' : AuditId,
  'status' : AuditStatus,
  'completedAt' : IDL.Opt(IDL.Int),
  'overallScore' : IDL.Opt(IDL.Float64),
  'createdAt' : IDL.Int,
  'riskTier' : IDL.Opt(RiskTier),
  'deploymentContext' : IDL.Text,
  'modelVersion' : IDL.Opt(IDL.Text),
  'modelName' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const AuditResults = IDL.Record({
  'biasResults' : IDL.Opt(IDL.Text),
  'inputSummary' : IDL.Opt(IDL.Text),
  'regulatoryResults' : IDL.Opt(IDL.Text),
  'overallScore' : IDL.Opt(IDL.Float64),
  'recommendations' : IDL.Opt(IDL.Text),
  'safetyResults' : IDL.Opt(IDL.Text),
  'riskTier' : IDL.Opt(RiskTier),
  'verdict' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAudit' : IDL.Func([AuditInput], [AuditId], []),
  'generateApiKey' : IDL.Func([], [IDL.Text], []),
  'getAudit' : IDL.Func([AuditId], [IDL.Opt(AuditRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
  'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyRecord)], ['query']),
  'listAudits' : IDL.Func([], [IDL.Vec(AuditSummary)], []),
  'runAudit' : IDL.Func([AuditId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAuditResults' : IDL.Func([AuditId, AuditResults], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuditInput = IDL.Record({
    'inputCsvUrl' : IDL.Opt(IDL.Text),
    'inputText' : IDL.Opt(IDL.Text),
    'selectedBiasDimensions' : IDL.Vec(IDL.Text),
    'summaryTone' : IDL.Text,
    'modelProvider' : IDL.Opt(IDL.Text),
    'jurisdiction' : IDL.Text,
    'selectedSafetyChecks' : IDL.Vec(IDL.Text),
    'deploymentContext' : IDL.Text,
    'outputCount' : IDL.Opt(IDL.Nat),
    'modelVersion' : IDL.Opt(IDL.Text),
    'modelName' : IDL.Text,
    'reportTitle' : IDL.Opt(IDL.Text),
    'intendedPopulation' : IDL.Text,
    'selectedFrameworks' : IDL.Vec(IDL.Text),
  });
  const AuditId = IDL.Text;
  const AuditStatus = IDL.Variant({
    'pending' : IDL.Null,
    'complete' : IDL.Null,
    'processing' : IDL.Null,
    'failed' : IDL.Null,
  });
  const RiskTier = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  });
  const AuditRecord = IDL.Record({
    'id' : AuditId,
    'status' : AuditStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'biasResults' : IDL.Opt(IDL.Text),
    'inputCsvUrl' : IDL.Opt(IDL.Text),
    'inputText' : IDL.Opt(IDL.Text),
    'inputSummary' : IDL.Opt(IDL.Text),
    'regulatoryResults' : IDL.Opt(IDL.Text),
    'selectedBiasDimensions' : IDL.Vec(IDL.Text),
    'overallScore' : IDL.Opt(IDL.Float64),
    'summaryTone' : IDL.Text,
    'orgId' : IDL.Text,
    'recommendations' : IDL.Opt(IDL.Text),
    'createdAt' : IDL.Int,
    'createdBy' : IDL.Text,
    'safetyResults' : IDL.Opt(IDL.Text),
    'riskTier' : IDL.Opt(RiskTier),
    'modelProvider' : IDL.Opt(IDL.Text),
    'verdict' : IDL.Opt(IDL.Text),
    'jurisdiction' : IDL.Text,
    'selectedSafetyChecks' : IDL.Vec(IDL.Text),
    'deploymentContext' : IDL.Text,
    'outputCount' : IDL.Opt(IDL.Nat),
    'modelVersion' : IDL.Opt(IDL.Text),
    'modelName' : IDL.Text,
    'reportTitle' : IDL.Opt(IDL.Text),
    'intendedPopulation' : IDL.Text,
    'selectedFrameworks' : IDL.Vec(IDL.Text),
  });
  const DashboardStats = IDL.Record({
    'reportsGenerated' : IDL.Nat,
    'totalAudits' : IDL.Nat,
    'avgRiskScore' : IDL.Float64,
    'openIssues' : IDL.Nat,
  });
  const ActivityEvent = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'auditId' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'eventType' : IDL.Text,
  });
  const ApiKeyRecord = IDL.Record({
    'id' : IDL.Text,
    'key' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'lastUsed' : IDL.Opt(IDL.Int),
  });
  const AuditSummary = IDL.Record({
    'id' : AuditId,
    'status' : AuditStatus,
    'completedAt' : IDL.Opt(IDL.Int),
    'overallScore' : IDL.Opt(IDL.Float64),
    'createdAt' : IDL.Int,
    'riskTier' : IDL.Opt(RiskTier),
    'deploymentContext' : IDL.Text,
    'modelVersion' : IDL.Opt(IDL.Text),
    'modelName' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const AuditResults = IDL.Record({
    'biasResults' : IDL.Opt(IDL.Text),
    'inputSummary' : IDL.Opt(IDL.Text),
    'regulatoryResults' : IDL.Opt(IDL.Text),
    'overallScore' : IDL.Opt(IDL.Float64),
    'recommendations' : IDL.Opt(IDL.Text),
    'safetyResults' : IDL.Opt(IDL.Text),
    'riskTier' : IDL.Opt(RiskTier),
    'verdict' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAudit' : IDL.Func([AuditInput], [AuditId], []),
    'generateApiKey' : IDL.Func([], [IDL.Text], []),
    'getAudit' : IDL.Func([AuditId], [IDL.Opt(AuditRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActivityFeed' : IDL.Func([], [IDL.Vec(ActivityEvent)], ['query']),
    'listApiKeys' : IDL.Func([], [IDL.Vec(ApiKeyRecord)], ['query']),
    'listAudits' : IDL.Func([], [IDL.Vec(AuditSummary)], []),
    'runAudit' : IDL.Func([AuditId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAuditResults' : IDL.Func([AuditId, AuditResults], [], []),
  });
};

export const init = ({ IDL }) => { return []; };