/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityEvent {
  'id' : string,
  'description' : string,
  'auditId' : [] | [string],
  'timestamp' : bigint,
  'eventType' : string,
}
export interface ApiKeyRecord {
  'id' : string,
  'key' : string,
  'name' : string,
  'createdAt' : bigint,
  'lastUsed' : [] | [bigint],
}
export type AuditId = string;
export interface AuditInput {
  'inputCsvUrl' : [] | [string],
  'inputText' : [] | [string],
  'selectedBiasDimensions' : Array<string>,
  'summaryTone' : string,
  'modelProvider' : [] | [string],
  'jurisdiction' : string,
  'selectedSafetyChecks' : Array<string>,
  'deploymentContext' : string,
  'outputCount' : [] | [bigint],
  'modelVersion' : [] | [string],
  'modelName' : string,
  'reportTitle' : [] | [string],
  'intendedPopulation' : string,
  'selectedFrameworks' : Array<string>,
}
export interface AuditRecord {
  'id' : AuditId,
  'status' : AuditStatus,
  'completedAt' : [] | [bigint],
  'biasResults' : [] | [string],
  'inputCsvUrl' : [] | [string],
  'inputText' : [] | [string],
  'inputSummary' : [] | [string],
  'regulatoryResults' : [] | [string],
  'selectedBiasDimensions' : Array<string>,
  'overallScore' : [] | [number],
  'summaryTone' : string,
  'orgId' : string,
  'recommendations' : [] | [string],
  'createdAt' : bigint,
  'createdBy' : string,
  'safetyResults' : [] | [string],
  'riskTier' : [] | [RiskTier],
  'modelProvider' : [] | [string],
  'verdict' : [] | [string],
  'jurisdiction' : string,
  'selectedSafetyChecks' : Array<string>,
  'deploymentContext' : string,
  'outputCount' : [] | [bigint],
  'modelVersion' : [] | [string],
  'modelName' : string,
  'reportTitle' : [] | [string],
  'intendedPopulation' : string,
  'selectedFrameworks' : Array<string>,
}
export interface AuditResults {
  'biasResults' : [] | [string],
  'inputSummary' : [] | [string],
  'regulatoryResults' : [] | [string],
  'overallScore' : [] | [number],
  'recommendations' : [] | [string],
  'safetyResults' : [] | [string],
  'riskTier' : [] | [RiskTier],
  'verdict' : [] | [string],
}
export type AuditStatus = { 'pending' : null } |
  { 'complete' : null } |
  { 'processing' : null } |
  { 'failed' : null };
export interface AuditSummary {
  'id' : AuditId,
  'status' : AuditStatus,
  'completedAt' : [] | [bigint],
  'overallScore' : [] | [number],
  'createdAt' : bigint,
  'riskTier' : [] | [RiskTier],
  'deploymentContext' : string,
  'modelVersion' : [] | [string],
  'modelName' : string,
}
export interface DashboardStats {
  'reportsGenerated' : bigint,
  'totalAudits' : bigint,
  'avgRiskScore' : number,
  'openIssues' : bigint,
}
export type RiskTier = { 'low' : null } |
  { 'high' : null } |
  { 'critical' : null } |
  { 'medium' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAudit' : ActorMethod<[AuditInput], AuditId>,
  'generateApiKey' : ActorMethod<[], string>,
  'getAudit' : ActorMethod<[AuditId], [] | [AuditRecord]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActivityFeed' : ActorMethod<[], Array<ActivityEvent>>,
  'listApiKeys' : ActorMethod<[], Array<ApiKeyRecord>>,
  'listAudits' : ActorMethod<[], Array<AuditSummary>>,
  'runAudit' : ActorMethod<[AuditId], undefined>,
  'setAnthropicApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAuditResults' : ActorMethod<[AuditId, AuditResults], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];