/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DashboardStats {
    reportsGenerated: bigint;
    totalAudits: bigint;
    avgRiskScore: number;
    openIssues: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface AuditRecord {
    id: AuditId;
    status: AuditStatus;
    completedAt?: bigint;
    biasResults?: string;
    inputCsvUrl?: string;
    inputText?: string;
    inputSummary?: string;
    regulatoryResults?: string;
    selectedBiasDimensions: Array<string>;
    overallScore?: number;
    summaryTone: string;
    orgId: string;
    recommendations?: string;
    createdAt: bigint;
    createdBy: string;
    safetyResults?: string;
    riskTier?: RiskTier;
    modelProvider?: string;
    verdict?: string;
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount?: bigint;
    modelVersion?: string;
    modelName: string;
    reportTitle?: string;
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
}
export interface AuditSummary {
    id: AuditId;
    status: AuditStatus;
    completedAt?: bigint;
    overallScore?: number;
    createdAt: bigint;
    riskTier?: RiskTier;
    deploymentContext: string;
    modelVersion?: string;
    modelName: string;
}
export type AuditId = string;
export interface ActivityEvent {
    id: string;
    description: string;
    auditId?: string;
    timestamp: bigint;
    eventType: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AuditInput {
    inputCsvUrl?: string;
    inputText?: string;
    selectedBiasDimensions: Array<string>;
    summaryTone: string;
    modelProvider?: string;
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount?: bigint;
    modelVersion?: string;
    modelName: string;
    reportTitle?: string;
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
}
export interface AuditResults {
    biasResults?: string;
    inputSummary?: string;
    regulatoryResults?: string;
    overallScore?: number;
    recommendations?: string;
    safetyResults?: string;
    riskTier?: RiskTier;
    verdict?: string;
}
export interface ApiKeyRecord {
    id: string;
    key: string;
    name: string;
    createdAt: bigint;
    lastUsed?: bigint;
}
export enum AuditStatus {
    pending = "pending",
    complete = "complete",
    processing = "processing",
    failed = "failed"
}
export enum RiskTier {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAudit(input: AuditInput): Promise<AuditId>;
    generateApiKey(): Promise<string>;
    getAudit(id: AuditId): Promise<AuditRecord | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    isCallerAdmin(): Promise<boolean>;
    listActivityFeed(): Promise<Array<ActivityEvent>>;
    listApiKeys(): Promise<Array<ApiKeyRecord>>;
    listAudits(): Promise<Array<AuditSummary>>;
    runAudit(id: AuditId): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAuditResults(id: AuditId, results: AuditResults): Promise<void>;
}
import type { ActivityEvent as _ActivityEvent, ApiKeyRecord as _ApiKeyRecord, AuditId as _AuditId, AuditInput as _AuditInput, AuditRecord as _AuditRecord, AuditResults as _AuditResults, AuditStatus as _AuditStatus, AuditSummary as _AuditSummary, RiskTier as _RiskTier, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAudit(arg0: AuditInput): Promise<AuditId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAudit(to_candid_AuditInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAudit(to_candid_AuditInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateApiKey();
            return result;
        }
    }
    async getAudit(arg0: AuditId): Promise<AuditRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudit(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudit(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActivityFeed(): Promise<Array<ActivityEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActivityFeed();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActivityFeed();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async listApiKeys(): Promise<Array<ApiKeyRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApiKeys();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApiKeys();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAudits(): Promise<Array<AuditSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAudits();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAudits();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async runAudit(arg0: AuditId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runAudit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runAudit(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAuditResults(arg0: AuditId, arg1: AuditResults): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAuditResults(arg0, to_candid_AuditResults_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAuditResults(arg0, to_candid_AuditResults_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ActivityEvent_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityEvent): ActivityEvent {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ApiKeyRecord_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiKeyRecord): ApiKeyRecord {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_AuditRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditRecord): AuditRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_AuditStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditStatus): AuditStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AuditSummary_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditSummary): AuditSummary {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_RiskTier_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RiskTier): RiskTier {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RiskTier]): RiskTier | null {
    return value.length === 0 ? null : from_candid_RiskTier_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AuditRecord]): AuditRecord | null {
    return value.length === 0 ? null : from_candid_AuditRecord_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    description: string;
    auditId: [] | [string];
    timestamp: bigint;
    eventType: string;
}): {
    id: string;
    description: string;
    auditId?: string;
    timestamp: bigint;
    eventType: string;
} {
    return {
        id: value.id,
        description: value.description,
        auditId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.auditId)),
        timestamp: value.timestamp,
        eventType: value.eventType
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    key: string;
    name: string;
    createdAt: bigint;
    lastUsed: [] | [bigint];
}): {
    id: string;
    key: string;
    name: string;
    createdAt: bigint;
    lastUsed?: bigint;
} {
    return {
        id: value.id,
        key: value.key,
        name: value.name,
        createdAt: value.createdAt,
        lastUsed: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.lastUsed))
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditId;
    status: _AuditStatus;
    completedAt: [] | [bigint];
    overallScore: [] | [number];
    createdAt: bigint;
    riskTier: [] | [_RiskTier];
    deploymentContext: string;
    modelVersion: [] | [string];
    modelName: string;
}): {
    id: AuditId;
    status: AuditStatus;
    completedAt?: bigint;
    overallScore?: number;
    createdAt: bigint;
    riskTier?: RiskTier;
    deploymentContext: string;
    modelVersion?: string;
    modelName: string;
} {
    return {
        id: value.id,
        status: from_candid_AuditStatus_n8(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.completedAt)),
        overallScore: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.overallScore)),
        createdAt: value.createdAt,
        riskTier: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.riskTier)),
        deploymentContext: value.deploymentContext,
        modelVersion: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.modelVersion)),
        modelName: value.modelName
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditId;
    status: _AuditStatus;
    completedAt: [] | [bigint];
    biasResults: [] | [string];
    inputCsvUrl: [] | [string];
    inputText: [] | [string];
    inputSummary: [] | [string];
    regulatoryResults: [] | [string];
    selectedBiasDimensions: Array<string>;
    overallScore: [] | [number];
    summaryTone: string;
    orgId: string;
    recommendations: [] | [string];
    createdAt: bigint;
    createdBy: string;
    safetyResults: [] | [string];
    riskTier: [] | [_RiskTier];
    modelProvider: [] | [string];
    verdict: [] | [string];
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount: [] | [bigint];
    modelVersion: [] | [string];
    modelName: string;
    reportTitle: [] | [string];
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
}): {
    id: AuditId;
    status: AuditStatus;
    completedAt?: bigint;
    biasResults?: string;
    inputCsvUrl?: string;
    inputText?: string;
    inputSummary?: string;
    regulatoryResults?: string;
    selectedBiasDimensions: Array<string>;
    overallScore?: number;
    summaryTone: string;
    orgId: string;
    recommendations?: string;
    createdAt: bigint;
    createdBy: string;
    safetyResults?: string;
    riskTier?: RiskTier;
    modelProvider?: string;
    verdict?: string;
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount?: bigint;
    modelVersion?: string;
    modelName: string;
    reportTitle?: string;
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_AuditStatus_n8(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.completedAt)),
        biasResults: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.biasResults)),
        inputCsvUrl: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.inputCsvUrl)),
        inputText: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.inputText)),
        inputSummary: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.inputSummary)),
        regulatoryResults: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.regulatoryResults)),
        selectedBiasDimensions: value.selectedBiasDimensions,
        overallScore: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.overallScore)),
        summaryTone: value.summaryTone,
        orgId: value.orgId,
        recommendations: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.recommendations)),
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        safetyResults: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.safetyResults)),
        riskTier: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.riskTier)),
        modelProvider: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.modelProvider)),
        verdict: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.verdict)),
        jurisdiction: value.jurisdiction,
        selectedSafetyChecks: value.selectedSafetyChecks,
        deploymentContext: value.deploymentContext,
        outputCount: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.outputCount)),
        modelVersion: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.modelVersion)),
        modelName: value.modelName,
        reportTitle: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.reportTitle)),
        intendedPopulation: value.intendedPopulation,
        selectedFrameworks: value.selectedFrameworks
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): RiskTier {
    return "low" in value ? RiskTier.low : "high" in value ? RiskTier.high : "critical" in value ? RiskTier.critical : "medium" in value ? RiskTier.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    complete: null;
} | {
    processing: null;
} | {
    failed: null;
}): AuditStatus {
    return "pending" in value ? AuditStatus.pending : "complete" in value ? AuditStatus.complete : "processing" in value ? AuditStatus.processing : "failed" in value ? AuditStatus.failed : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityEvent>): Array<ActivityEvent> {
    return value.map((x)=>from_candid_ActivityEvent_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiKeyRecord>): Array<ApiKeyRecord> {
    return value.map((x)=>from_candid_ApiKeyRecord_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditSummary>): Array<AuditSummary> {
    return value.map((x)=>from_candid_AuditSummary_n26(_uploadFile, _downloadFile, x));
}
function to_candid_AuditInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditInput): _AuditInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AuditResults_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditResults): _AuditResults {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_RiskTier_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTier): _RiskTier {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    biasResults?: string;
    inputSummary?: string;
    regulatoryResults?: string;
    overallScore?: number;
    recommendations?: string;
    safetyResults?: string;
    riskTier?: RiskTier;
    verdict?: string;
}): {
    biasResults: [] | [string];
    inputSummary: [] | [string];
    regulatoryResults: [] | [string];
    overallScore: [] | [number];
    recommendations: [] | [string];
    safetyResults: [] | [string];
    riskTier: [] | [_RiskTier];
    verdict: [] | [string];
} {
    return {
        biasResults: value.biasResults ? candid_some(value.biasResults) : candid_none(),
        inputSummary: value.inputSummary ? candid_some(value.inputSummary) : candid_none(),
        regulatoryResults: value.regulatoryResults ? candid_some(value.regulatoryResults) : candid_none(),
        overallScore: value.overallScore ? candid_some(value.overallScore) : candid_none(),
        recommendations: value.recommendations ? candid_some(value.recommendations) : candid_none(),
        safetyResults: value.safetyResults ? candid_some(value.safetyResults) : candid_none(),
        riskTier: value.riskTier ? candid_some(to_candid_RiskTier_n30(_uploadFile, _downloadFile, value.riskTier)) : candid_none(),
        verdict: value.verdict ? candid_some(value.verdict) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inputCsvUrl?: string;
    inputText?: string;
    selectedBiasDimensions: Array<string>;
    summaryTone: string;
    modelProvider?: string;
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount?: bigint;
    modelVersion?: string;
    modelName: string;
    reportTitle?: string;
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
}): {
    inputCsvUrl: [] | [string];
    inputText: [] | [string];
    selectedBiasDimensions: Array<string>;
    summaryTone: string;
    modelProvider: [] | [string];
    jurisdiction: string;
    selectedSafetyChecks: Array<string>;
    deploymentContext: string;
    outputCount: [] | [bigint];
    modelVersion: [] | [string];
    modelName: string;
    reportTitle: [] | [string];
    intendedPopulation: string;
    selectedFrameworks: Array<string>;
} {
    return {
        inputCsvUrl: value.inputCsvUrl ? candid_some(value.inputCsvUrl) : candid_none(),
        inputText: value.inputText ? candid_some(value.inputText) : candid_none(),
        selectedBiasDimensions: value.selectedBiasDimensions,
        summaryTone: value.summaryTone,
        modelProvider: value.modelProvider ? candid_some(value.modelProvider) : candid_none(),
        jurisdiction: value.jurisdiction,
        selectedSafetyChecks: value.selectedSafetyChecks,
        deploymentContext: value.deploymentContext,
        outputCount: value.outputCount ? candid_some(value.outputCount) : candid_none(),
        modelVersion: value.modelVersion ? candid_some(value.modelVersion) : candid_none(),
        modelName: value.modelName,
        reportTitle: value.reportTitle ? candid_some(value.reportTitle) : candid_none(),
        intendedPopulation: value.intendedPopulation,
        selectedFrameworks: value.selectedFrameworks
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RiskTier): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == RiskTier.low ? {
        low: null
    } : value == RiskTier.high ? {
        high: null
    } : value == RiskTier.critical ? {
        critical: null
    } : value == RiskTier.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
